# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/PyCQA/isort 
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["-l", "100", "--profile", "black"]
        exclude: 'app/resources.py'
-   repo: https://github.com/psf/black 
    rev: 24.1.1
    hooks:
    -   id: black
        args: ["-S", "-l", "100"]
        exclude: 'app/resources.py'

